/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_authenticated/admin'
import { Route as AdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AdminStudiesRouteImport } from './routes/_authenticated/admin/studies'
import { Route as AdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AdminBlockchainRouteImport } from './routes/_authenticated/admin/blockchain'
import { Route as AdminFraudRouteImport } from './routes/_authenticated/admin/fraud'
import { Route as AdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResearcherRouteImport } from './routes/_authenticated/researcher'
import { Route as AuthenticatedParticipantRouteImport } from './routes/_authenticated/participant'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/_authenticated/admin/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/_authenticated/admin/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudiesRoute = AdminStudiesRouteImport.update({
  id: '/_authenticated/admin/studies',
  path: '/studies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/_authenticated/admin/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlockchainRoute = AdminBlockchainRouteImport.update({
  id: '/_authenticated/admin/blockchain',
  path: '/blockchain',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/_authenticated/admin/fraud',
  path: '/fraud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/_authenticated/admin/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/_authenticated/admin/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/_authenticated/admin/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/_authenticated/admin/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/_authenticated/admin/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResearcherRoute = AuthenticatedResearcherRouteImport.update({
  id: '/researcher',
  path: '/researcher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParticipantRoute =
  AuthenticatedParticipantRouteImport.update({
    id: '/participant',
    path: '/participant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/participant': typeof AuthenticatedParticipantRoute
  '/researcher': typeof AuthenticatedResearcherRoute
  '/admin': typeof AdminIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/studies': typeof AdminStudiesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/blockchain': typeof AdminBlockchainRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/participant': typeof AuthenticatedParticipantRoute
  '/researcher': typeof AuthenticatedResearcherRoute
  '/admin': typeof AdminIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/studies': typeof AdminStudiesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/blockchain': typeof AdminBlockchainRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/participant': typeof AuthenticatedParticipantRoute
  '/_authenticated/researcher': typeof AuthenticatedResearcherRoute
  '/admin': typeof AdminIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/studies': typeof AdminStudiesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/blockchain': typeof AdminBlockchainRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/participant'
    | '/researcher'
    | '/admin'
    | '/admin/'
    | '/admin/users'
    | '/admin/studies'
    | '/admin/payments'
    | '/admin/blockchain'
    | '/admin/fraud'
    | '/admin/analytics'
    | '/admin/reports'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/support'
    | '/admin'
    | '/admin/'
    | '/admin/users'
    | '/admin/studies'
    | '/admin/payments'
    | '/admin/blockchain'
    | '/admin/fraud'
    | '/admin/analytics'
    | '/admin/reports'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/participant'
    | '/researcher'
    | '/admin'
    | '/admin/'
    | '/admin/users'
    | '/admin/studies'
    | '/admin/payments'
    | '/admin/blockchain'
    | '/admin/fraud'
    | '/admin/analytics'
    | '/admin/reports'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/support'
    | '/admin'
    | '/admin/'
    | '/admin/users'
    | '/admin/studies'
    | '/admin/payments'
    | '/admin/blockchain'
    | '/admin/fraud'
    | '/admin/analytics'
    | '/admin/reports'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/support'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/participant'
    | '/_authenticated/researcher'
    | '/_authenticated/admin'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/studies'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/blockchain'
    | '/_authenticated/admin/fraud'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/researcher': {
      id: '/_authenticated/researcher'
      path: '/researcher'
      fullPath: '/researcher'
      preLoaderRoute: typeof AuthenticatedResearcherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/participant': {
      id: '/_authenticated/participant'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof AuthenticatedParticipantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/studies': {
      id: '/_authenticated/admin/studies'
      path: '/studies'
      fullPath: '/admin/studies'
      preLoaderRoute: typeof AdminStudiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/blockchain': {
      id: '/_authenticated/admin/blockchain'
      path: '/blockchain'
      fullPath: '/admin/blockchain'
      preLoaderRoute: typeof AdminBlockchainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/fraud': {
      id: '/_authenticated/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminStudiesRoute: typeof AdminStudiesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminBlockchainRoute: typeof AdminBlockchainRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminStudiesRoute: AdminStudiesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminBlockchainRoute: AdminBlockchainRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedParticipantRoute: typeof AuthenticatedParticipantRoute
  AuthenticatedResearcherRoute: typeof AuthenticatedResearcherRoute
  AdminRoute: typeof AdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedParticipantRoute: AuthenticatedParticipantRoute,
  AuthenticatedResearcherRoute: AuthenticatedResearcherRoute,
  AdminRoute: AdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
